name: Build, Lint and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  check-skippable:
    continue-on-error: true
    runs-on: ubuntu-22.04
    permissions:
      actions: write
      contents: read
    timeout-minutes: 10
    outputs:
      skippable: ${{ steps.check.outputs.should_skip }}
    steps:
      - id: check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2

  test:
    name: Test
    needs: check-skippable
    if: needs.check-skippable.outputs.skippable != 'true'
    permissions:
      contents: read
      actions: read
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - 16.14.0
          - 18
          - 20
          - 22
        experimental:
          - false
        include:
          - os: windows-latest
            # latest LTS
            node-version: 20
            experimental: false
          - os: macos-latest
            # latest LTS
            node-version: 20
            experimental: false
          - os: ubuntu-22.04
            node-version: 23-nightly
            experimental: true

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          # Set to true to publish the results as comment to the PR (applicable if workflow run is triggered by PR).
          comment_on_pr: false

      - name: Checkout the source
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          standalone: true

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm test

  build-lint:
    name: Build and Lint
    needs: check-skippable
    if: needs.check-skippable.outputs.skippable != 'true'
    permissions:
      contents: read
      actions: read
    timeout-minutes: 10

    # Using matrix strategy, OS and Node version will be displayed in a title of a job.
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          # oldest LTS
          - 18

    runs-on: ${{ matrix.os }}

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0

      - name: Checkout the source
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          standalone: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm lint

  action-timeline:
    needs:
      - check-skippable
      - test
      - build-lint
    continue-on-error: true
    runs-on: ubuntu-22.04
    permissions:
      actions: read
    timeout-minutes: 10
    steps:
      - uses: Kesin11/actions-timeline@7c7e0821d38f27460f4a71ef874a1c8cf23602e4 # v2.2.6
