name: Build, Lint, Test and Release
on:
  push:
    branches:
      - main

concurrency: release

jobs:
  build-lint-test:
    uses: ./.github/workflows/build-lint-test.yml
    permissions:
      actions: write
      contents: read

  release:
    needs: build-lint-test

    permissions:
      # create a PR
      contents: write
      pull-requests: write
      # Publishing packages with provenance
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 # v1.4.7
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
